export interface MarketplaceAgent {
  id: string;
  name: string;
  description: string;
  category: string;
  categoryColor: string;
  price: string;
  priceValue: number;
  rating: number;
  reviews: number;
  installs: string;
  creator: string;
  creatorAvatar: string;
  tags: string[];
  featured: boolean;
  trending: boolean;
  verified: boolean;
  lastUpdated: string;
  executionsPerMonth: string;
}

export const marketplaceAgents: MarketplaceAgent[] = [
  {
    id: "sales-pipeline-orchestrator",
    name: "Sales Pipeline Orchestrator",
    description: "Automates lead scoring, follow-ups, deal progression, and CRM updates across your entire sales funnel.",
    category: "Business",
    categoryColor: "text-yellow-400 bg-yellow-900/30 ring-yellow-400/30",
    price: "$49/mo",
    priceValue: 49,
    rating: 4.9,
    reviews: 2347,
    installs: "12.4k",
    creator: "SalesForge AI",
    creatorAvatar: "SF",
    tags: ["CRM", "Lead Scoring", "Automation"],
    featured: true,
    trending: true,
    verified: true,
    lastUpdated: "2 days ago",
    executionsPerMonth: "~2,500",
  },
  {
    id: "security-scanner-pro",
    name: "Security Scanner Pro",
    description: "Continuous vulnerability scanning, compliance monitoring, and automated incident response for cloud infrastructure.",
    category: "Infrastructure",
    categoryColor: "text-red-400 bg-red-900/30 ring-red-400/30",
    price: "$199/mo",
    priceValue: 199,
    rating: 4.8,
    reviews: 1823,
    installs: "8.7k",
    creator: "CyberShield Labs",
    creatorAvatar: "CS",
    tags: ["Security", "Compliance", "Cloud"],
    featured: true,
    trending: false,
    verified: true,
    lastUpdated: "5 days ago",
    executionsPerMonth: "~5,000",
  },
  {
    id: "content-engine",
    name: "Content Engine",
    description: "AI-powered content creation, scheduling, and distribution across multiple channels with SEO optimization.",
    category: "Workflow",
    categoryColor: "text-purple-400 bg-purple-900/30 ring-purple-400/30",
    price: "$79/mo",
    priceValue: 79,
    rating: 4.7,
    reviews: 3142,
    installs: "18.2k",
    creator: "ContentFlow AI",
    creatorAvatar: "CF",
    tags: ["Content", "SEO", "Social Media"],
    featured: true,
    trending: true,
    verified: true,
    lastUpdated: "1 day ago",
    executionsPerMonth: "~3,200",
  },
  {
    id: "cicd-pipeline-manager",
    name: "CI/CD Pipeline Manager",
    description: "Intelligent deployment orchestration with rollback detection, canary analysis, and multi-cloud support.",
    category: "DevOps",
    categoryColor: "text-orange-400 bg-orange-900/30 ring-orange-400/30",
    price: "$149/mo",
    priceValue: 149,
    rating: 4.9,
    reviews: 4218,
    installs: "22.1k",
    creator: "DevOps Collective",
    creatorAvatar: "DC",
    tags: ["CI/CD", "Deployment", "Multi-Cloud"],
    featured: true,
    trending: true,
    verified: true,
    lastUpdated: "3 days ago",
    executionsPerMonth: "~8,000",
  },
  {
    id: "lead-qualifier-ai",
    name: "Lead Qualifier AI",
    description: "Automatically scores and qualifies inbound leads using behavioral signals, firmographics, and intent data.",
    category: "Business",
    categoryColor: "text-yellow-400 bg-yellow-900/30 ring-yellow-400/30",
    price: "$39/mo",
    priceValue: 39,
    rating: 4.6,
    reviews: 5721,
    installs: "31.5k",
    creator: "LeadGen Pro",
    creatorAvatar: "LG",
    tags: ["Leads", "Scoring", "Intent"],
    featured: false,
    trending: true,
    verified: true,
    lastUpdated: "1 week ago",
    executionsPerMonth: "~1,800",
  },
  {
    id: "incident-responder",
    name: "Incident Responder",
    description: "Automated incident triage, escalation, and resolution with PagerDuty, Slack, and Jira integrations.",
    category: "Security",
    categoryColor: "text-red-400 bg-red-900/30 ring-red-400/30",
    price: "$249/mo",
    priceValue: 249,
    rating: 4.8,
    reviews: 1247,
    installs: "6.3k",
    creator: "IncidentAI",
    creatorAvatar: "IA",
    tags: ["Incidents", "On-Call", "Triage"],
    featured: true,
    trending: false,
    verified: true,
    lastUpdated: "4 days ago",
    executionsPerMonth: "~4,500",
  },
  {
    id: "email-automation-suite",
    name: "Email Automation Suite",
    description: "Smart email sorting, auto-responses, follow-up scheduling, and inbox zero automation.",
    category: "Utility",
    categoryColor: "text-blue-400 bg-blue-900/30 ring-blue-400/30",
    price: "$19/mo",
    priceValue: 19,
    rating: 4.5,
    reviews: 8412,
    installs: "45.2k",
    creator: "InboxZero Co",
    creatorAvatar: "IZ",
    tags: ["Email", "Productivity", "Automation"],
    featured: false,
    trending: true,
    verified: true,
    lastUpdated: "6 days ago",
    executionsPerMonth: "~900",
  },
  {
    id: "data-pipeline-builder",
    name: "Data Pipeline Builder",
    description: "Visual ETL pipeline creation with 50+ connectors, data validation, and real-time streaming support.",
    category: "Workflow",
    categoryColor: "text-purple-400 bg-purple-900/30 ring-purple-400/30",
    price: "$99/mo",
    priceValue: 99,
    rating: 4.7,
    reviews: 2934,
    installs: "14.8k",
    creator: "DataFlow Labs",
    creatorAvatar: "DL",
    tags: ["ETL", "Data", "Streaming"],
    featured: true,
    trending: false,
    verified: true,
    lastUpdated: "2 days ago",
    executionsPerMonth: "~6,000",
  },
  {
    id: "customer-success-bot",
    name: "Customer Success Bot",
    description: "Proactive churn detection, health scoring, and automated customer outreach based on usage patterns.",
    category: "Business",
    categoryColor: "text-yellow-400 bg-yellow-900/30 ring-yellow-400/30",
    price: "$59/mo",
    priceValue: 59,
    rating: 4.6,
    reviews: 1876,
    installs: "9.1k",
    creator: "SuccessAI",
    creatorAvatar: "SA",
    tags: ["Churn", "Health Score", "Outreach"],
    featured: false,
    trending: true,
    verified: true,
    lastUpdated: "3 days ago",
    executionsPerMonth: "~2,100",
  },
  {
    id: "compliance-monitor",
    name: "Compliance Monitor",
    description: "Continuous compliance checking against SOC2, HIPAA, GDPR, and PCI-DSS with automated remediation.",
    category: "Infrastructure",
    categoryColor: "text-red-400 bg-red-900/30 ring-red-400/30",
    price: "$219/mo",
    priceValue: 219,
    rating: 4.8,
    reviews: 982,
    installs: "4.2k",
    creator: "ComplianceAI",
    creatorAvatar: "CA",
    tags: ["SOC2", "HIPAA", "GDPR"],
    featured: true,
    trending: false,
    verified: true,
    lastUpdated: "1 week ago",
    executionsPerMonth: "~3,800",
  },
  {
    id: "slack-workflow-bot",
    name: "Slack Workflow Bot",
    description: "Automate team workflows directly from Slack with natural language commands and approval flows.",
    category: "Utility",
    categoryColor: "text-blue-400 bg-blue-900/30 ring-blue-400/30",
    price: "$14/mo",
    priceValue: 14,
    rating: 4.4,
    reviews: 6234,
    installs: "38.7k",
    creator: "SlackOps",
    creatorAvatar: "SO",
    tags: ["Slack", "Workflows", "Commands"],
    featured: false,
    trending: true,
    verified: true,
    lastUpdated: "5 days ago",
    executionsPerMonth: "~600",
  },
  {
    id: "meeting-summarizer",
    name: "Meeting Summarizer",
    description: "Auto-joins meetings, transcribes, extracts action items, and distributes summaries to attendees.",
    category: "Utility",
    categoryColor: "text-blue-400 bg-blue-900/30 ring-blue-400/30",
    price: "Free",
    priceValue: 0,
    rating: 4.3,
    reviews: 12847,
    installs: "67.3k",
    creator: "Community",
    creatorAvatar: "CM",
    tags: ["Meetings", "Transcription", "Notes"],
    featured: false,
    trending: true,
    verified: false,
    lastUpdated: "2 weeks ago",
    executionsPerMonth: "~200",
  },
];

export const marketplaceStats = {
  totalAgents: 527,
  totalInstalls: "2.4M+",
  totalCreators: 189,
  avgRating: 4.6,
  categoryCounts: {
    "Business": 142,
    "Workflow": 98,
    "Utility": 124,
    "Infrastructure": 67,
    "Security": 54,
    "DevOps": 42,
  },
};
